"""Add quantity and unit_price to transactions

Revision ID: 0d3d35ef2626
Revises: a806fc6e487e
Create Date: 2026-02-20 14:09:04.459672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3d35ef2626'
down_revision = 'a806fc6e487e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('unit_price')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
