"""Add recurring_transactions table

Revision ID: 87e83aafa51f
Revises: 661e65431196
Create Date: 2026-03-05 08:25:10.337663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e83aafa51f'
down_revision = '661e65431196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('last_created_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("frequency IN ('daily', 'weekly', 'monthly', 'yearly')", name='check_recurring_frequency'),
    sa.CheckConstraint("transaction_type IN ('income', 'expense')", name='check_recurring_transaction_type'),
    sa.CheckConstraint('amount > 0', name='check_recurring_positive_amount'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_transactions_next_due_date'), ['next_due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_transactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_transactions_next_due_date'))

    op.drop_table('recurring_transactions')
    # ### end Alembic commands ###
