"""Add is_active and email_notifications to User model

Revision ID: cacddf17d405
Revises: 639c25ba0da0
Create Date: 2026-02-20 18:32:27.387346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cacddf17d405'
down_revision = '639c25ba0da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server_default for existing rows
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=False, server_default='true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
